# -*- coding: utf-8 -*-
"""checkout_ab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17d_wKm-ZKz2KN8ZdsGqtUXR976ei6wTP

### Import Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

"""### Load Dataset"""

df =pd.read_csv('/content/checkout_ab_test.csv' ,parse_dates=['signup_date'])
df.head()

"""### Explore Dataset Dimensions and Duplicates"""

print(f'Columns:{df.shape[1]}')
print(f'rows:{len(df):,}')
print(f'Unique users: {df.user_id.nunique():,}')
print(f'Duplicate rows: {len(df)-df.user_id.nunique():,}')
print(f'missing values: {df.isna().sum().sum()}' )

"""### Remove Duplicates and Rename Column"""

ab = df.drop_duplicates(subset='user_id', keep='first').copy()
ab = ab.rename(columns={'group':'test_group'})
print(ab)

"""### Check Group Split"""

split = ab.test_group.value_counts()
expected = [len(ab)/2 , len(ab)/2]
chi2, p_split = stats.chisquare(f_obs=split.values, f_exp=expected)

display(split.to_frame('users').assign(pct=lambda d: d.users/len(ab)))
print(f'chi2 = {chi2:.3f}, p = {p_split:.3f}')

"""### Calculate Summary Statistics by Test Group"""

summary = ab.groupby('test_group').agg(
    users=('user_id','size'),
    buyers=('purchased','sum'),
    conversion_rate=('purchased','mean'),
    revenue_per_user=('revenue','mean'),
)
summary['avg_order_value'] = ab.groupby('test_group')['revenue'].sum() / summary['buyers']
summary

"""### Calculate Absolute and Relative Lift"""

p_ctrl = summary.loc['control' , 'conversion_rate']
p_trt = summary.loc['treatment' , 'conversion_rate']
n_ctrl = summary.loc['control' , 'users']
n_trt = summary.loc['treatment' , 'users']
x_ctrl = summary.loc['control' , 'buyers']
x_trt = summary.loc['treatment' , 'buyers']

absolute_lift = p_trt - p_ctrl
relative_lift = absolute_lift / p_ctrl

print(f'control: {p_ctrl: .2%}')
print(f'treatment: {p_trt: .2%}')
print(f'absolute_lift: {absolute_lift*100:+.2f} percentage points')
print(f'relative_lift: {relative_lift:+.1%}')

"""### Perform Z-Test for Conversion Rates"""

p_pooled = (x_ctrl + x_trt) / (n_ctrl + n_trt)
se_pooled = np.sqrt(p_pooled * (1-p_pooled) * (1/n_ctrl + 1/n_trt))
z = (p_trt - p_ctrl) / se_pooled
p_value = 2 * (1 - stats.norm.cdf(abs(z)))  # two-sided

print(f'pooled rate    = {p_pooled:.5f}')
print(f'standard error = {se_pooled:.6f}')
print(f'z score        = {z:.3f}')
print(f'p value        = {p_value:.8f}')

"""### Calculate Confidence Interval for Lift"""

se_diff = np.sqrt(p_ctrl*(1-p_ctrl)/n_ctrl + p_trt*(1-p_trt)/n_trt)
ci_low  = (absolute_lift - 1.96*se_diff) * 100
ci_high = (absolute_lift + 1.96*se_diff) * 100

print(f'unpooled SE = {se_diff:.6f}')
print(f'Lift {absolute_lift*100:+.2f} points, 95% CI [{ci_low:+.2f}, {ci_high:+.2f}]')

"""### Display Conversion Rates with Confidence Intervals"""

rows = []
for arm in ['control', 'treatment']:
    p_ = summary.loc[arm , 'conversion_rate']
    n_ = summary.loc[arm , 'users']
    se_= np.sqrt(p_ * (1-p_) / n_)
    rows.append({'group': arm, 'rate': p_,
                 'ci_low': p_ - 1.96*se_, 'ci_high': p_ + 1.96*se_})
pd.DataFrame(rows).set_index('group')

"""### Calculate Minimum Detectable Effect (MDE)"""

from statsmodels.stats.power import NormalIndPower

def mde(baseline, n1, n2, power=0.80, alpha=0.05):
    """Smallest detectable lift, in percentage points."""
    h = NormalIndPower().solve_power(effect_size=None, nobs1=int(n1), alpha=alpha,
                                     power=power, ratio=n2/n1, alternative='two-sided')
    # solve_power works in Cohen's h; convert back to a real rate
    detectable = np.sin(np.arcsin(np.sqrt(baseline)) + h/2)**2
    return (detectable - baseline) * 100

mde_pp = mde(p_ctrl, n_ctrl, n_trt)

print(f'Baseline:  {p_ctrl:.2%}')
print(f'Sample:    {int(n_ctrl):,} vs {int(n_trt):,}')
print(f'MDE (80%): {mde_pp:+.2f} pp ({mde_pp/(p_ctrl*100):+.1%} relative)')
print(f'Observed:  {absolute_lift*100:+.2f} pp')

"""### Analyze Conversion Rates by Device"""

by_device = ab.pivot_table(index='device',columns='test_group',
                           values='purchased', aggfunc='mean') * 100
by_device['lift'] = by_device['treatment'] - by_device['control']
by_device.round(2)

"""### Analyze Conversion Rates by Sign-up Date"""

by_day = ab.pivot_table(index='signup_date', columns='test_group',
                       values='purchased', aggfunc='mean') * 100
by_day.round(2)

"""### Visualize Conversion Rates"""

fig, axes = plt.subplots(1, 2, figsize=(11, 4))

rates, errs = [], []
for arm in ['control', 'treatment']:
    p_ = summary.loc[arm , 'conversion_rate']
    n_ = summary.loc[arm , 'users']
    rates.append(p_ * 100)
    errs.append(1.96 * np.sqrt(p_*(1-p_)/n_) * 100)

axes[0].bar(['Control', 'Treatment'], rates, yerr=errs, capsize=6,
            color=['#999999', '#2E86AB'])
axes[0].set_ylabel('Conversion rate (%)')
axes[0].set_title('Conversion rate (95% CI)')
for i, r in enumerate(rates):
    axes[0].text(i, r + errs[i] + 0.3, f'{r:.2f}%', ha='center')


by_day.plot(ax=axes[1], marker='o', color=['#999999', '#2E86AB'])
axes[1].set_ylabel('Conversion rate (%)')
axes[1].set_xlabel('')
axes[1].set_title('Conversion by day')
axes[1].legend(title='')

plt.tight_layout()
plt.show()